# Academic code for the Transmission Line courses at Universidad Nacional de Colombia.
# No warranty of any kind; not for real-world design. See DISCLAIMER.md.
# License: to be defined (open source intended); until then all rights reserved.
# This code is generated by ChatGPT asking to compute the distance between two points in a figure 
# based on a distance from the object and a knonw distance
# April 2025

import cv2
import numpy as np

ref_points = []
focal_length = None
known_distance = None
known_real_size = None
image = None
clone = None

def click_event(event, x, y, flags, param):
    global ref_points, focal_length, known_distance, known_real_size, clone

    if event == cv2.EVENT_LBUTTONDOWN:
        ref_points.append((x, y))
        cv2.circle(clone, (x, y), 5, (0, 255, 0), -1)
        cv2.imshow("Image", clone)

        if len(ref_points) == 2 and focal_length is None:
            # Calibration step
            pixel_size = euclidean(ref_points[0], ref_points[1])
            known_distance = float(input("Enter distance from camera to object (in [m])"))
            known_real_size = float(input("Enter real-world size of selected object feature in [m]: "))
            focal_length = (pixel_size * known_distance) / known_real_size
            print(f"[INFO] Calibrated focal length: {focal_length:.2f} pixels")

            cv2.line(clone, ref_points[0], ref_points[1], (255, 0, 0), 2)
            ref_points = []

        elif len(ref_points) == 2 and focal_length is not None:
            # Measurement step
            pixel_size = euclidean(ref_points[0], ref_points[1])
            real_size = (pixel_size * known_distance) / focal_length
            print(f"[INFO] Measured real-world size: {real_size:.2f} m")

            cv2.line(clone, ref_points[0], ref_points[1], (0, 0, 255), 2)
            cv2.putText(clone, f"{real_size:.2f} m", midpoint(ref_points[0], ref_points[1]),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
            ref_points = []

def midpoint(ptA, ptB):
    return (int((ptA[0] + ptB[0]) / 2), int((ptA[1] + ptB[1]) / 2))

def euclidean(ptA, ptB):
    return np.linalg.norm(np.array(ptA) - np.array(ptB))

def main():
    global image, clone

    image_path = input("Enter path to image: ")
    image = cv2.imread(image_path)
    if image is None:
        print("[ERROR] Could not load image.")
        return

    clone = image.copy()
    cv2.imshow("Image", clone)
    cv2.setMouseCallback("Image", click_event)
    print("[INFO] First, click 2 points on an object of known size and known distance.")
    print("[INFO] Then, click any two points to measure unknown real-world size.")
    print("[INFO] Press 'r' to reset or 'q' to quit.")

    while True:
        key = cv2.waitKey(1) & 0xFF
        if key == ord('r'):
            reset()
        elif key == ord('q'):
            break

    cv2.destroyAllWindows()

def reset():
    global clone, ref_points, focal_length
    clone[:] = image.copy()
    ref_points.clear()
    print("[INFO] Reset done.")
    cv2.imshow("Image", clone)

if __name__ == "__main__":
    main()
